# Generated by Django 3.1.6 on 2021-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20210501_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-01 09:27:05.922395'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('inprocess', 'Inprocess')], default='Inprocess', max_length=50),
        ),
    ]
